### ISSUE TITLE
`writeToJson` or `writeToJsonMap` keys

### ISSUE THREAD

**Issue by opyate** [dart-lang/protobuf#184]
I've noticed `writeToJson` or `writeToJsonMap` keys are protobuf indeces instead of field names.

I need to send off an incoming protobuf payload to an external service via a JSON web API, so what would be the best way to override the keys? A custom mixin? Would it break anything that relies on the map to stay as it is?

**Comment by sigurdm** [comment]
Du I  understand correctly you want to generate json that uses field names instead of tag-numbers as keys?

We have a (unfortunately very stale) PR implementing this: https://github.com/dart-lang/protobuf/pull/83 .
This is indeed a feature we want. I hope we get around integrating that PR or something like it soon.

**Comment by opyate** [comment]
You understood me correctly, yes.

**Comment by opyate** [comment]
I'll close this and keep an eye on the PR.

**Comment by sh0umik** [comment]
I need this support badly. :(
