### ISSUE TITLE
Can't load Kernel binary: Invalid kernel binary format version.

### ISSUE THREAD

**Issue by ansarizafar** [dart-lang/protobuf#359]
I am using latest version but I am getting this error
````
Can't load Kernel binary: Invalid kernel binary format version.
/home/zafar/flutter/.pub-cache/bin/protoc-gen-dart: 16: /home/zafar/flutter/.pub-cache/bin/protoc-gen-dart: pub: not found
````

**Comment by sigurdm** [comment]
Hmm - it sounds like you have updated the dart vm, but pub is updating the globally installed script.

Could you try `pub global deactivate protoc_plugin` followed by `pub global activate protoc_plugin`

If that does not work were gonna need more details

**Comment by ansarizafar** [comment]
I was using 
```
flutter pub global activate protoc_plugin
```
but when I installed dart separately and used the following command the issued is resolved. Thanks
````
pub global activate protoc_plugin
````

**Comment by sigurdm** [comment]
So this was an issue with incompatible dart versions.

Perhaps pub should detect this, and give a message, or even recompile?
@jonasfj what do you think?

**Comment by jonasfj** [comment]
Yeah, this seems like a bug in `pub`, I actually thought we had some code handling this.

**Comment by khainke** [comment]
experienced the same issue, just without `pub:not found`.
After installing with 
```bash
flutter pub global activate protoc_plugin
```
And using protoc with the protoc_plugin from the flutter pub cache, this error appears:
```bash
Can't load Kernel binary: Invalid kernel binary format version.
```

**Comment by MateusAmin** [comment]
At first I got a 'Dart Not Found' error. Two things:

1. In turns out the Flutter snap install on Ubuntu does not install the dart clit tools.
2. the proto cli cannot compensate for flutter only

Installed Dart with the .deb package, and pub installed the plugin. Now I get:

Can't load Kernel binary: Invalid kernel binary format version.

**Comment by zaher-recode** [comment]
I just had the same issue after upgrading to flutter 1.20, I guess since flutter includes dart sdk now, 
`pub global activate protoc_plugin` doesn't work any more.

just deactivated  it `pub global deactivate protoc_plugin` and then run `flutter pub global activate protoc_plugin`  add the new path / remove the previous one and voila, it works again.

**Comment by George35mk** [comment]
I get the error today after the upgrade of Flutter SDK to v3.7.0, I was using protoc_plugin v20.0.0

First I deactivated the plugin and then I activated again.

```
dart pub global deactivate protoc_plugin
dart pub global activate protoc_plugin
```

```
Activated protoc_plugin 20.0.1.
```
