### ISSUE TITLE
Support field names instead of only tag numbers in fromJson 

### ISSUE THREAD

**Issue by BlackHC** [dart-lang/protobuf#37]
Right now, only tag numbers are supported. It would be great if we would also support using the fieldnames for interoperability with parsing JSON-encoded protobufs from other languages (eg Java or Python). See eg https://github.com/dpp-name/protobuf-json 's output

**Comment by skybrian** [comment]
In general, it isn't a good idea to put field names into the wire protocol because then renaming a field breaks backward compatibility. Part of the point of protos is that the field names are for developers and only the tag numbers have any consequence in production.

So I think the best fix is that these other languages should support JSON-encoding protobufs using tag numbers. This is how Google's web apps generally work for best performance, so it's the encoding I'm going to focus on. But I'm not completely against it, since having the field names is admittedly more useful when debugging.

As a workaround, you could try the Streamy library which I believe uses field names?
https://github.com/google/streamy-dart

**Comment by skybrian** [comment]
I've received enough requests for alternate JSON encodings that I'll probably work on this soon.

**Comment by skybrian** [comment]
Well, that didn't happen. At this point let's just say it's a good idea that nobody is working on.

**Comment by BlackHC** [comment]
Sorry for not replying earlier. Is there a short document with your idea
how to implement this? Then maybe a 20% contributor could have a look at
some point. I'm more than drowning in work too atm though :/
Thanks,
Andreas

**Comment by skybrian** [comment]
No design doc. But I think we're going to be supporting multiple JSON encodings for a while, so the new API should probably have a JsonEncoding enum with values for JsonP (current protocol), Proto3, and possibly others. The caller should pass in the one they want to use.

**Comment by sigurdm** [comment]
I believe this is the same as: https://github.com/dart-lang/protobuf/issues/220
Closing as duplicate.
