### ISSUE TITLE
Errors on assign nullable values

### ISSUE THREAD

**Issue by zs-dima** [dart-lang/protobuf#432]
Error `Unsupported operation: Attempted to change a read-only message (google.protobuf.Int32Value)`
on trying to assign nullable values.

We have proto file:
```
message SomeObject {
	google.protobuf.Int32Value property1 = 1;
	google.protobuf.BoolValue property2 = 2;
	google.protobuf.BytesValue property3 = 3;
* * *
}
```

Then we have auto-generated Int32Value object fields and trying to set them to create new object to send to the server:

```Dart
final value = 5;
var someObject = SomeObject();
someObject.property1 = value == null ? Int32Value.getDefault() : (Int32Value()..value = value);
```

Then we have error: `Unsupported operation: Attempted to change a read-only message (google.protobuf.Int32Value)`

Could you please provide way or workaround to set object fields?

**Comment by zs-dima** [comment]
After source code investigation I found workaround, but it is really ugly.
I am a bit confused of this strange style to set field, and do not know why developers could select it and had not even documented:

```Dart
final value = 5;
var someObject = SomeObject();
someObject.property1 = value == null ? Int32Value.getDefault() : Int32Value()..setField(1, value);
```

**Comment by iinozemtsev** [comment]
`(Int32Value()..value = value)` should work fine, what could be a problem is that if you use `Int32Value.getDefault()`, and then assign value later:

```
var someObject = SomeObject()..property1 = Int32Value.getDefault();
someObject.property1.value = 5; // <-- that will fail.
```

Or, if you omit braces around `(Int32Value()..value = value)`, you'll get an error because of cascade and ternary operators precedence order:

```
someObject.property1 = value == null ? Int32Value.getDefault() : Int32Value()..value = value;
```

In general, I prefer to use just constructors instead of `getDefault()`, as `getDefault()` returns a shared immutable instance of an empty message.

Also, using a cascade operator on `SomeObject()`, your code may look like this:

```
    var someObject = SomeObject()
      ..property1 =
          (value == null ? Int32Value() : (Int32Value()..value = value));
```
