### ISSUE TITLE
Consider implementing PbList iteration methods directly

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/protobuf#76]
PbList uses ListMixin to provide various iteration functions (e.g. `contains`, `any`, `every`).  The ListMixin versions of these functions are fairly inefficient - they check the length getter once or twice per iteration in order to catch concurrent modification.  It feels like concurrent modification is pretty small concern for this code, and I've seen uses of `contains` specifically showing up in fairly hot positions in internal customer code.  I've confirmed that dart2js is not able to eliminate the extra checks, nor is it inlining the `length` getter to expose the underlying list length getter.  Since the methods are therefore presumably shared by all of the different code that mixes in ListMixin, my guess is that this is highly polymorphic and probably pretty slow.

It seems worthwhile to me to explicitly implement the main iteration functions in PbList directly, since this code is fairly performance sensitive.

Relevant:

https://github.com/dart-lang/sdk/issues/30478
https://github.com/dart-lang/sdk/issues/30477

**Comment by rakudrama** [comment]
PbList is a wrapper over a regular list. dart2js can infer `_wrappedList` is implemented as a JavaScript `Array` (because it is a final field always initialized via a List literal or List constructor.)
PbList implements the mutating part of the List interface so that the values stored into the list can be validated (e.g. prevent `null` values from being be stored).

PbList could easily be modified to delegate the non-mutating methods to `_wrappedList`.
I see a lot of calls to `single`, `first`, `isNotEmpty` so these should definitely be delegated.

If you also delegate iterable-producing methods, especially `map` and `where`, there will be a benefit from planned changes to the JSArray implementation.

**Comment by jakobr-google** [comment]
So, `PbList` should really just stop using `ListMixin`, right?

**Comment by rakudrama** [comment]
I would remove `ListMixin`, add all the missing methods, then add `ListMixin` back so that `PbList` will still compile if a method is added to Iterable or List for Dart 2.0.
